const mongoose = require("mongoose");
var schema = mongoose.Schema(
  {
    id: String,
    domain: String,
    publisher: String,
    source_url: String,
    advertiser_name: String,
    app_developer: String,
    logo_url: String,
    app_type: Number,
    os: Number,
    title: String,
    body: String,
    message: String,
    preview_img_url: String,
    resource_urls: [
      {
        image_url: String,
        video_url: String,
        s3_image_url: String,
        s3_video_url: String,
      },
    ],
    cdn_url: [String],
    call_to_action_type: String,
    store_url: String,
    first_seen: { type: String, index: true },
    last_seen: { type: String, index: true },
    platform: Number,
    type: Number,
    like_count: String,
    comment_count: String,
    share_count: String,
    view_count: String,
    dislike_count: String,
    pin: Number,
    heat: String,
    impression: String,
    days_count: String,
    page_id: String,
    post_id: String,
    page_name: String,
    categoryTag: [String],
    post_url: String,
    feature_ads_flag: Number,
    track_flag: Number,
    textMd5: String,
    dynamic_number: Number,
    category: [String],
    theme: [String],
    game_play: [String],
    game_style: [String],
    ad_width: Number,
    ad_height: Number,
    ads_format: String,
    relate_ads: Number,
    language: String,
    created_date: String,
    html_url: String,
    countries: [String],
    source_url: String,
    multi_advertiser_names: [String],
    redirect_urls: [String],
  },
  { timestamps: true }
);
const Ads = mongoose.model("ads", schema);
module.exports = Ads;
